Fix build for mac osx
After run make:

mkdir -p bin/
cc -o bin/pcs.o -c -fPIC -D_FILE_OFFSET_BITS=64 pcs/pcs.c
pcs/pcs.c:10:11: fatal error: 'openssl/md5.h' file not found
...

Try to install openssl:

brew install openssl

Apple has deprecated use of OpenSSL in favor of its own TLS and crypto
libraries

Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

	LDFLAGS:  -L/usr/local/opt/openssl/lib
	CPPFLAGS: -I/usr/local/opt/openssl/include

Also, compiler says "clang: warning: -largp: 'linker' input unused", so remove it.